set(CMAKE_SYSTEM_NAME Windows)

include(${CMAKE_CURRENT_LIST_DIR}/msvc42-common.cmake)

set(CMAKE_C_COMPILER ${CMAKE_SOURCE_DIR}/cmake/Toolchain/wrappers/cl)
set(CMAKE_CXX_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_RC_COMPILER ${CMAKE_SOURCE_DIR}/cmake/Toolchain/wrappers/rc)
set(CMAKE_AR ${CMAKE_SOURCE_DIR}/cmake/Toolchain/wrappers/lib)
set(CMAKE_LINKER ${CMAKE_SOURCE_DIR}/cmake/Toolchain/wrappers/link)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
