set(CMAKE_SYSTEM_NAME Windows)

include(${CMAKE_CURRENT_LIST_DIR}/msvc42-common.cmake)

set(CMAKE_C_COMPILER $ENV{ISLE_KIT_ROOT}/msvc420/bin/cl.exe)
set(CMAKE_CXX_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_RC_COMPILER $ENV{ISLE_KIT_ROOT}/msvc420/bin/rc.exe)
set(CMAKE_AR $ENV{ISLE_KIT_ROOT}/msvc420/bin/lib.exe)
set(CMAKE_LINKER $ENV{ISLE_KIT_ROOT}/msvc420/bin/link.exe)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_COMPILER_WORKS ON)
set(CMAKE_CXX_COMPILER_WORKS ON)
