// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef CARRACER_ACTIONS_H
#define CARRACER_ACTIONS_H

namespace CarracerScript
{
#if __cplusplus >= 201103L
enum Script : int {
#else
enum Script {
#endif
	c_noneCarracer = -1,

	c_nrt002pz_Anim = 0,
	c_NRT100DR_Anim = 1,
	c_NRT110DR_Anim = 2,
	c_NRT101DR_Anim = 3,
	c_NRT111DR_Anim = 4,
	c_NRT102DR_Anim = 5,
	c_NRT112DR_Anim = 6,
	c_NRT103DR_Anim = 7,
	c_NRT113DR_Anim = 8,
	c_NRT104DR_Anim = 9,
	c_NRT114DR_Anim = 10,
	c_NRT105DR_Anim = 11,
	c_NRT115DR_Anim = 12,
	c_NRT106DR_Anim = 13,
	c_NRT116DR_Anim = 14,
	c_NRT107DR_Anim = 15,
	c_NRT117DR_Anim = 16,
	c_NRT108DR_Anim = 17,
	c_NRT118DR_Anim = 18,
	c_NRT109DR_Anim = 19,
	c_NRT119DR_Anim = 20,
	c_nrt015gh_RunAnim = 21,
	c_nrt001pz_RunAnim = 22,
	c_nrt002pz_RunAnim = 23,
	c_nrt030bk_RunAnim = 24,
	c_nrt031bk_RunAnim = 25,
	c_nrt032bk_RunAnim = 26,
	c_nrt025sw_RunAnim = 27,
	c_nrt004sh_RunAnim = 28,
	c_nrt003sh_RunAnim = 29,
	c_nrt022sp_RunAnim = 30,
	c_nrt015sl_RunAnim = 31,
	c_nrt014sl_RunAnim = 32,
	c_nrt013sl_RunAnim = 33,
	c_nrt012sl_RunAnim = 34,
	c_nrt026sw_RunAnim = 35,
	c_nrt027sw_RunAnim = 36,
	c_nrt028sw_RunAnim = 37,
	c_nrt029sw_RunAnim = 38,
	c_nrt033bk_RunAnim = 39,
	c_nrt034bk_RunAnim = 40,
	c_nrt035bk_RunAnim = 41,
	c_nrt016gh_RunAnim = 42,
	c_nrt030sw_RunAnim = 43,
	c_nrt005ft_RunAnim = 44,
	c_nrt010pz_RunAnim = 45,
	c_nrt011pz_RunAnim = 46,
	c_nrt008oc_RunAnim = 47,
	c_nrt003sh_Anim = 48,
	c_nrt004sh_Anim = 49,
	c_nrt005ft_Anim = 50,
	c_nrt008oc_Anim = 51,
	c_nrt010pz_Anim = 52,
	c_nrt011pz_Anim = 53,
	c_nrt012sl_Anim = 54,
	c_nrt013sl_Anim = 55,
	c_nrt014sl_Anim = 56,
	c_nrt015gh_Anim = 57,
	c_nrt015sl_Anim = 58,
	c_nrt016gh_Anim = 59,
	c_nrt026sw_Anim = 60,
	c_nrt027sw_Anim = 61,
	c_nrt028sw_Anim = 62,
	c_nrt029sw_Anim = 63,
	c_nrt031bk_Anim = 64,
	c_nrt032bk_Anim = 65,
	c_nrt035bk_Anim = 66,
	c_nrt025sw_Anim = 67,
	c_nrt022sp_Anim = 68,
	c_nrt030sw_Anim = 69,

	c_TRS100_BlackSky = 100,

	c_TRS200_DkBlueSky = 200,

	c_TRS300_BlackSky = 300,

	c_TRS400_BlueSky = 400
};
} // namespace CarracerScript

#endif // CARRACER_ACTIONS_H
