// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef CREDITS_ACTIONS_H
#define CREDITS_ACTIONS_H

namespace CreditsScript
{
#if __cplusplus >= 201103L
enum Script : int {
#else
enum Script {
#endif
	c_noneCredits = -1,

	c_Credits_Wav = 0,
	c_Credits_Smk = 1,
	c_Credit01_Bitmap = 2,
	c_Credit02_Bitmap = 3,
	c_Credit03_Bitmap = 4,
	c_Credit04_Bitmap = 5,
	c_Credit05_Bitmap = 6,
	c_Credit06_Bitmap = 7,
	c_Credit07_Bitmap = 8,
	c_Credit08_Bitmap = 9,
	c_Credit09_Bitmap = 10,
	c_Credit11_Bitmap = 11,
	c_Credit12_Bitmap = 12,
	c_Credit13_Bitmap = 13,
	c_Credit14_Bitmap = 14,
	c_Credit15_Bitmap = 15,
	c_Credit16_Bitmap = 16,
	c_Credit17_Bitmap = 17,
	c_Credit21_Bitmap = 18,
	c_Credit19_Bitmap = 19,
	c_Credit22_Bitmap = 20,
	c_Credit22b_Bitmap = 21,
	c_Credit25_Bitmap = 22,
	c_Credit20_Bitmap = 23,
	c_Credit12b_Bitmap = 24,
	c_Credit23_Bitmap = 25,
	c_Credit24_Bitmap = 26,
	c_Credit14b_Bitmap = 27,
	c_Credit14c_Bitmap = 28,
	c_Credit26_Bitmap = 29,
	c_Credit27_Bitmap = 30,
	c_Credit28_Bitmap = 31,
	c_Credit29_Bitmap = 32,
	c_Credit10_Bitmap = 33,
	c_Credit17b_Bitmap = 34,
	c_Credit17c_Bitmap = 35,

	c_LegoCredits = 499
};
} // namespace CreditsScript

#endif // CREDITS_ACTIONS_H
