// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef ELEVBOTT_ACTIONS_H
#define ELEVBOTT_ACTIONS_H

namespace ElevbottScript
{
#ifdef COMPAT_MODE
enum Script : int {
#else
enum Script {
#endif
	c_noneElevbott = -1,

	c__StartUp = 0,
	c_LeftArrow_Ctl = 1,
	c_RightArrow_Ctl = 2,
	c_ElevBott_Elevator_Ctl = 3,
	c_Background_Bitmap = 4,
	c_LeftArrow_Up_Bitmap = 5,
	c_LeftArrow_Down_Bitmap = 6,
	c_RightArrow_Up_Bitmap = 7,
	c_RightArrow_Down_Bitmap = 8,
	c_Elevator_Mask_Bitmap = 9,
	c_ConfigAnimation = 10,

	c_iica31in_PlayWav = 500
};
} // namespace ElevbottScript

#endif // ELEVBOTT_ACTIONS_H
