// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef HISTBOOK_ACTIONS_H
#define HISTBOOK_ACTIONS_H

namespace HistbookScript
{
#if __cplusplus >= 201103L
enum Script : int {
#else
enum Script {
#endif
	c_noneHistbook = -1,

	c__StartUp = 0,
	c_ScoreBox = 1,
	c_Background_Bitmap = 2,
	c_A_Bitmap = 3,
	c_B_Bitmap = 4,
	c_C_Bitmap = 5,
	c_D_Bitmap = 6,
	c_E_Bitmap = 7,
	c_F_Bitmap = 8,
	c_G_Bitmap = 9,
	c_H_Bitmap = 10,
	c_I_Bitmap = 11,
	c_J_Bitmap = 12,
	c_K_Bitmap = 13,
	c_L_Bitmap = 14,
	c_M_Bitmap = 15,
	c_N_Bitmap = 16,
	c_O_Bitmap = 17,
	c_P_Bitmap = 18,
	c_Q_Bitmap = 19,
	c_R_Bitmap = 20,
	c_S_Bitmap = 21,
	c_T_Bitmap = 22,
	c_U_Bitmap = 23,
	c_V_Bitmap = 24,
	c_W_Bitmap = 25,
	c_X_Bitmap = 26,
	c_Y_Bitmap = 27,
	c_Z_Bitmap = 28
};
} // namespace HistbookScript

#endif // HISTBOOK_ACTIONS_H
