// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef INFODOOR_ACTIONS_H
#define INFODOOR_ACTIONS_H

namespace InfodoorScript
{
#ifdef COMPAT_MODE
enum Script : int {
#else
enum Script {
#endif
	c_noneInfodoor = -1,

	c__StartUp = 0,
	c_LeftArrow_Ctl = 1,
	c_RightArrow_Ctl = 2,
	c_Info_Ctl = 3,
	c_Door_Ctl = 4,
	c_Background_Bitmap = 5,
	c_LeftArrow_Up_Bitmap = 6,
	c_LeftArrow_Down_Bitmap = 7,
	c_RightArrow_Up_Bitmap = 8,
	c_RightArrow_Down_Bitmap = 9,
	c_Info_Up_Bitmap = 10,
	c_Info_Down_Bitmap = 11,
	c_Door_Up_Bitmap = 12,
	c_ConfigAnimation = 13,

	c_iic037in_PlayWav = 500,
	c_iic038in_PlayWav = 501,
	c_iicb31in_PlayWav = 502,
	c_iic007in_PlayWav = 503
};
} // namespace InfodoorScript

#endif // INFODOOR_ACTIONS_H
