// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef INFOSCOR_ACTIONS_H
#define INFOSCOR_ACTIONS_H

namespace InfoscorScript
{
#if __cplusplus >= 201103L
enum Script : int {
#else
enum Script {
#endif
	c_noneInfoscor = -1,

	c__StartUp = 0,
	c_LeftArrow_Ctl = 1,
	c_RightArrow_Ctl = 2,
	c_Book_Ctl = 3,
	c_LegoBox_Ctl = 4,
	c_HistBook_Bmp = 5,
	c_HistBook_Flc = 6,
	c_LegoBox1_Flc = 7,
	c_LegoBox2_Flc = 8,
	c_LegoBox3_Flc = 9,
	c_GoTo_HistBook = 10,
	c_Background_Bitmap = 11,
	c_LeftArrow_Up_Bitmap = 12,
	c_LeftArrow_Down_Bitmap = 13,
	c_RightArrow_Up_Bitmap = 14,
	c_RightArrow_Down_Bitmap = 15,
	c_Book_Up_Bitmap = 16,
	c_LegoBox_Mask_Bitmap = 17,
	c_ConfigAnimation = 18,
	c_nin001pr_Anim = 19,

	c_nin001pr_RunAnim = 500,
	c_iicc31in_PlayWav = 501
};
} // namespace InfoscorScript

#endif // INFOSCOR_ACTIONS_H
