// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef INTRO_ACTIONS_H
#define INTRO_ACTIONS_H

namespace IntroScript
{
#ifdef COMPAT_MODE
enum Script : int {
#else
enum Script {
#endif
	c_noneIntro = -1,

	c_Lego_Movie = 0,
	c_Mindscape_Movie = 1,
	c_Intro_Movie = 2,
	c_Outro_Movie = 3,
	c_BadEnd_Movie = 4,
	c_GoodEnd_Movie = 5,
	c_Lego_Smk = 6,
	c_Lego_Wave = 7,
	c_Mindscape_Smk = 8,
	c_Mindscape_Wave = 9,
	c_Intro_Smk = 10,
	c_Intro_Wave = 11,
	c_Outro_Smk = 12,
	c_Outro_Wave = 13,
	c_BadEnd_Smk = 14,
	c_BadEnd_Wave = 15,
	c_GoodEnd_Smk = 16,
	c_GoodEnd_Wave = 17
};
} // namespace IntroScript

#endif // INTRO_ACTIONS_H
