// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef JETRACER_ACTIONS_H
#define JETRACER_ACTIONS_H

namespace JetracerScript
{
#ifdef COMPAT_MODE
enum Script : int {
#else
enum Script {
#endif
	c_noneJetracer = -1,

	c_Trigger200_Drown = 200,
	c_Trigger201_BtShark = 201,
	c_Trigger202_SwimShrk = 202,
	c_Trigger203_Hover_Anim = 203,
	c_Trigger204_SwimSj01 = 204,
	c_Trigger205_BtShark1 = 205,
	c_Trigger206_ShrkJum1 = 206,
	c_Trigger207_TriSpin = 207,
	c_Trigger208_TriSpin01 = 208,
	c_Trigger209_SwimBouy = 209,
	c_Trigger210_SwimSJ02 = 210
};
} // namespace JetracerScript

#endif // JETRACER_ACTIONS_H
