// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef JUKEBOX_ACTIONS_H
#define JUKEBOX_ACTIONS_H

namespace JukeboxScript
{
#if __cplusplus >= 201103L
enum Script : int {
#else
enum Script {
#endif
	c_noneJukebox = -1,

	c_MusicTheme1 = 0,
	c_MusicTheme3 = 1,
	c_Act2Cave = 2,
	c_BrickstrChase = 3,
	c_BrickHunt = 4,
	c_ResidentalArea_Music = 5,
	c_BeachBlvd_Music = 6,
	c_Cave_Music = 7,
	c_CentralRoads_Music = 8,
	c_Jail_Music = 9,
	c_Hospital_Music = 10,
	c_InformationCenter_Music = 11,
	c_PoliceStation_Music = 12,
	c_Park_Music = 13,
	c_CentralNorthRoad_Music = 14,
	c_GarageArea_Music = 15,
	c_RaceTrackRoad_Music = 16,
	c_Beach_Music = 17,
	c_Quiet_Audio = 18,
	c_JetskiRace_Music = 19,
	c_Act3Music = 20,
	c_sns002ra_Audio = 21,
	c_sns001ja_Audio = 22,
	c_snsc01js_Audio = 23,
	c_snsb01js_Audio = 24,
	c_snsa01js_Audio = 25,
	c_sns009ra_Audio = 26,
	c_ham035ra_Audio = 27,
	c_ham039ra_Audio = 28,
	c_sns005ra_Audio = 29,
	c_sns078pa_Audio = 30,
	c_ham036ra_Audio = 31,
	c_sns006ra_Audio = 32,
	c_sns013ra_Audio = 33,
	c_sns004ra_Audio = 34,
	c_sns079pa_Audio = 35,
	c_sns007ra_Audio = 36,
	c_sns008ra_Audio = 37,
	c_hpz037ma_Audio = 38,
	c_sns003ra_Audio = 39,
	c_sns010ra_Audio = 40,
	c_Radio1_Music = 41,
	c_Radio2_Music = 42,
	c_Radio3_Music = 43,
	c_Radio4_Music = 44,
	c_Radio5_Music = 45,
	c_Radio6_Music = 46,
	c_HelicopterBuild_Movie = 47,
	c_HelicopterBuild_Music = 48,
	c_DuneCarBuild_Movie = 49,
	c_DuneCarBuild_Music = 50,
	c_JetskiBuild_Movie = 51,
	c_JetskiBuild_Music = 52,
	c_RaceCarBuild_Movie = 53,
	c_RaceCarBuild_Music = 54,
	c_JBMusic1 = 55,
	c_JBMusic2 = 56,
	c_JBMusic3 = 57,
	c_JBMusic4 = 58,
	c_JBMusic5 = 59,
	c_JBMusic6 = 60,
	c_InfoCenter_3rd_Floor_Music = 61,
	c_Elevator_Music = 62,
	c_PizzaMission_Music = 63,
	c_HelicopterBuild_Flic = 64,
	c_DuneCarBuild_Flic = 65,
	c_JetskiBuild_Flic = 66,
	c_RaceCarBuild_Flic = 67
};
} // namespace JukeboxScript

#endif // JUKEBOX_ACTIONS_H
