// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef JUKEBOXW_ACTIONS_H
#define JUKEBOXW_ACTIONS_H

namespace JukeboxwScript
{
#if __cplusplus >= 201103L
enum Script : int {
#else
enum Script {
#endif
	c_noneJukeboxw = -1,

	c__StartUp = 0,
	c_Voldown_Ctl = 1,
	c_Volup_Ctl = 2,
	c_Dback_Ctl = 3,
	c_Dfwd_Ctl = 4,
	c_Note_Ctl = 5,
	c_Background_Bitmap = 6,
	c_Right_Bitmap = 7,
	c_Decal_Bitmap = 8,
	c_Wallis_Bitmap = 9,
	c_Nelson_Bitmap = 10,
	c_Torpedos_Bitmap = 11,
	c_Voldown_Up_Bitmap = 12,
	c_Voldown_Down_Bitmap = 13,
	c_Volup_Up_Bitmap = 14,
	c_Volup_Down_Bitmap = 15,
	c_Dback_Up_Bitmap = 16,
	c_Dback_Down_Bitmap = 17,
	c_Dfwd_Up_Bitmap = 18,
	c_Dfwd_Down_Bitmap = 19,
	c_Note_Up_Bitmap = 20,
	c_Note_Down_Bitmap = 21
};
} // namespace JukeboxwScript

#endif // JUKEBOXW_ACTIONS_H
