// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef NOCD_ACTIONS_H
#define NOCD_ACTIONS_H

class NocdScript {
public:
    enum Script {
        c_noneNocd = -1,

        c_NoCD_Movie = 0,
        c_CDSpin1_Smk = 1,
        c_Iicx62In_Wave = 2
    };
};

#endif // NOCD_ACTIONS_H
