// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef POLICE_ACTIONS_H
#define POLICE_ACTIONS_H

namespace PoliceScript
{
#if __cplusplus >= 201103L
enum Script : int {
#else
enum Script {
#endif
	c_nonePolice = -1,

	c__StartUp = 0,
	c_LeftArrow_Ctl = 1,
	c_RightArrow_Ctl = 2,
	c_Info_Ctl = 3,
	c_Door_Ctl = 4,
	c_Donut_Ctl = 5,
	c_Background_Bitmap = 6,
	c_LeftArrow_Up_Bitmap = 7,
	c_LeftArrow_Down_Bitmap = 8,
	c_RightArrow_Up_Bitmap = 9,
	c_RightArrow_Down_Bitmap = 10,
	c_Info_Up_Bitmap = 11,
	c_Info_Down_Bitmap = 12,
	c_Door_Mask_Bitmap = 13,
	c_Donut_Up_Bitmap = 14,
	c_Donut_Down_Bitmap = 15,
	c_RadioOff_Bitmap = 16,
	c_RadioOn_Bitmap = 17,
	c_Radio_Ctl = 18,
	c_ConfigAnimation = 19,
	c_nps001ni_0_sfx = 20,
	c_nps001ni_1_sfx = 21,
	c_nps001ni_2_sfx = 22,
	c_nps001ni_3_sfx = 23,
	c_nps001ni_4_sfx = 24,
	c_nps001ni_5_sfx = 25,
	c_nps001ni_Anim = 26,
	c_nps002la_0_sfx = 27,
	c_nps002la_1_sfx = 28,
	c_nps002la_2_sfx = 29,
	c_nps002la_3_sfx = 30,
	c_nps002la_4_sfx = 31,
	c_nps002la_5_sfx = 32,
	c_nps002la_Anim = 33,

	c_nps001ni_RunAnim = 500,
	c_nps002la_RunAnim = 501
};
} // namespace PoliceScript

#endif // POLICE_ACTIONS_H
