// This file was automatically generated by the actionheadergen tool.
// Please do not manually edit this file.
#ifndef SNDANIM_ACTIONS_H
#define SNDANIM_ACTIONS_H

namespace SndanimScript
{
#if __cplusplus >= 201103L
enum Script : int {
#else
enum Script {
#endif
	c_noneSndanim = -1,

	c_SoundAndAnim_Action = 0,

	c_ThisFilename = 4,

	c_AnimC1 = 10,
	c_AnimC2 = 11,
	c_AnimC3 = 12,
	c_AnimC4 = 13,

	c_AnimF1 = 30,
	c_AnimF2 = 31,
	c_AnimF3 = 32,
	c_AnimT1 = 33,
	c_AnimT2 = 34,
	c_AnimT3 = 35,
	c_AnimB1 = 36,
	c_AnimB2 = 37,
	c_AnimB3 = 38,
	c_AnimP1 = 39,
	c_AnimP2 = 40,
	c_AnimP3 = 41,

	c_Sound1 = 50,
	c_Sound2 = 51,
	c_Sound3 = 52,
	c_Sound4 = 53,
	c_Sound5 = 54,
	c_Sound6 = 55,
	c_Sound7 = 56,
	c_Sound8 = 57,
	c_Sound9 = 58,
	c_Sound10 = 59,
	c_Sound11 = 60,
	c_Sound12 = 61,
	c_Sound13 = 62,
	c_Sound14 = 63,
	c_Sound15 = 64,
	c_Sound16 = 65,
	c_Sound17 = 66,
	c_Sound18 = 67,
	c_Sound19 = 68,
	c_Sound20 = 69,
	c_AnimBld1 = 70,
	c_AnimBld2 = 71,
	c_AnimBld3 = 72,
	c_AnimBld4 = 73,
	c_AnimBld5 = 74,
	c_AnimBld6 = 75,
	c_AnimBld7 = 76,
	c_AnimBld8 = 77,
	c_AnimBld9 = 78,
	c_AnimBld10 = 79,
	c_AnimBld11 = 80,
	c_AnimBld12 = 81,
	c_AnimBld13 = 82,
	c_AnimBld14 = 83,
	c_AnimBld15 = 84,
	c_AnimBld16 = 85,
	c_AnimBld17 = 86,
	c_AnimBld18 = 87,

	c_TRS302_OpenJailDoor = 302,
	c_BRS303_CloseJailDoor = 303,

	c_BookWig_Flic = 400
};
} // namespace SndanimScript

#endif // SNDANIM_ACTIONS_H
