name: Analyze

on: [push, pull_request]

jobs:
  decomplint-isle:
    name: ${{ matrix.who }} annotations
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        who:
          - CONFIG
          - ISLE
          - LEGO1

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install python libraries
      run: |
        pip install -r tools/requirements.txt

    - name: Run decomplint.py
      run: |
        reccmp-decomplint ${{ matrix.who }} --module ${{ matrix.who }} --warnfail
