name: Analyze

on: [push, pull_request]

jobs:
  decomplint-isle:
    name: '${{ matrix.who }} annotations'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        who:
          - CONFIG
          - ISLE
          - LEGO1

    steps:
    - uses: actions/checkout@v4

    - name: Install python libraries
      run: |
        python -m pip install -r tools/requirements.txt

    - name: Run decomplint.py
      run: |
        tools/decomplint/decomplint.py ${{ matrix.who }} --module ${{ matrix.who }} --warnfail
