name: Analyze

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  decomplint-isle:
    name: ${{ matrix.who }} annotations
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        who:
          - CONFIG
          - ISLE
          - LEGO1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup Python modules
        run: |
          pip install -r tools/requirements.txt

      - name: Run decomplint.py
        run: |
          reccmp-decomplint ${{ matrix.who }} --module ${{ matrix.who }} --warnfail
