name: Check order

on: [push, pull_request]

jobs:
  checkorder:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install python libraries
      run: |
        pip install -r tools/requirements.txt

    - name: Run checkorder.py
      run: |
        python3 tools/checkorder/checkorder.py --verbose --enforce ISLE
        python3 tools/checkorder/checkorder.py --verbose --enforce LEGO1
